# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/SumbumsTeaTime',
                'doc_host': 'https://mildmill2.github.io',
                'git_url': 'https://github.com/mildmill2/{repo}',
                'lib_path': 'SumbumsTeaTime'},
  'syms': {'SumbumsTeaTime.core': {'SumbumsTeaTime.core.foo': ('nbs/core.html#foo', 'SumbumsTeaTime/core.py')}}}
