# Autogenerated by nbdev

d = { 'settings': {'branch': 'main', 'doc_baseurl': '/', 'doc_host': '', 'git_url': '', 'lib_path': ''},
  'syms': { 'SumbumsTeaTime.SumbumsTeaTime.core': { 'SumbumsTeaTime.SumbumsTeaTime.core.foo': ( 'core.html#foo',
                                                                                                'SumbumsTeaTime/SumbumsTeaTime/core.py')}}}
